### ISSUE TITLE
Don't work with quelpa argument :upgrade

### ISSUE THREAD

**Issue by bricewge** [jaccarmac/quse-package#1]
I didn't managed to use the quelpa argument `:upgrade` with your macro
For example in `(quelpa '(magit :repo "magit/magit" :branch "next" :fetcher github) :upgrade t)` is already compose of two lists but `quse-package` take only one list for the quelpa instructions.

**Comment by jaccarmac** [comment]
I will work on adding support for this. Apologies for not noticing the issue sooner; GitHub didn't give me a notification for some reason!

**Comment by jaccarmac** [comment]
Should work as of the latest release!
