### ISSUE TITLE
Possibly extending macro to add syntactic sugar like el-get-bundle

### ISSUE THREAD

**Issue by priyadarshan** [jaccarmac/quse-package#3]
Hi,

Thank you for `quse-package`, I just found out, and it is wonderful.

I was wondering if you could consider extending `quse-package` to add syntactic sugar like `el-get-bundle` does for `el-get`?

A brief description is here: https://github.com/dimitri/el-get#advanced-usage-with-local-recipes
The code is here: https://github.com/dimitri/el-get/blob/master/el-get-bundle.el

Thank you so much for `quse-package`.

**Comment by jaccarmac** [comment]
Not entirely sure what you're asking. `quse-package` is intended to wrap the functionality of `quelpa` and `use-package` into a single macro. `quelpa` already supports custom recipes of several kinds.

**Comment by priyadarshan** [comment]
Yes, I understand, it is preferred to keep `quse-package` focused.

Thank you.
